"""migration2

Revision ID: 1408a3ed85e7
Revises: 1a8d0ea547b5
Create Date: 2025-08-31 16:27:29.705161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1408a3ed85e7'
down_revision: Union[str, Sequence[str], None] = '1a8d0ea547b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Company', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge_hr_association',
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hr_id'], ['hr.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.PrimaryKeyConstraint('judge_id', 'hr_id')
    )
    op.create_table('judge_resume_association',
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('judge_id', 'resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judge_resume_association')
    op.drop_table('judge_hr_association')
    op.drop_table('judge')
    op.drop_table('hr')
    # ### end Alembic commands ###
