"""migration5 - changed relation between resume, judge, hr

Revision ID: 1b696c1efba1
Revises: 1ea4817712fc
Create Date: 2025-09-01 09:43:39.797828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b696c1efba1'
down_revision: Union[str, Sequence[str], None] = '1ea4817712fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judge_resume_association')
    op.drop_table('judge_hr_association')
    op.add_column('judge', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.add_column('judge', sa.Column('hr_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('judge_resumes_fkey'), 'judge', type_='foreignkey')
    op.create_foreign_key(None, 'judge', 'hr', ['hr_id'], ['id'])
    op.create_foreign_key(None, 'judge', 'resume', ['resume_id'], ['id'])
    op.drop_column('judge', 'resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge', sa.Column('resumes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'judge', type_='foreignkey')
    op.drop_constraint(None, 'judge', type_='foreignkey')
    op.create_foreign_key(op.f('judge_resumes_fkey'), 'judge', 'resume', ['resumes'], ['id'])
    op.drop_column('judge', 'hr_id')
    op.drop_column('judge', 'resume_id')
    op.create_table('judge_hr_association',
    sa.Column('judge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hr_id'], ['hr.id'], name=op.f('judge_hr_association_hr_id_fkey')),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], name=op.f('judge_hr_association_judge_id_fkey')),
    sa.PrimaryKeyConstraint('judge_id', 'hr_id', name=op.f('judge_hr_association_pkey'))
    )
    op.create_table('judge_resume_association',
    sa.Column('judge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], name=op.f('judge_resume_association_judge_id_fkey')),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name=op.f('judge_resume_association_resume_id_fkey')),
    sa.PrimaryKeyConstraint('judge_id', 'resume_id', name=op.f('judge_resume_association_pkey'))
    )
    # ### end Alembic commands ###
