"""migration4 - adjustments

Revision ID: 1ea4817712fc
Revises: f770cf7f3e93
Create Date: 2025-08-31 17:57:38.188547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea4817712fc'
down_revision: Union[str, Sequence[str], None] = 'f770cf7f3e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge', sa.Column('resumes', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'judge', 'resume', ['resumes'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judge', type_='foreignkey')
    op.drop_column('judge', 'resumes')
    # ### end Alembic commands ###
