"""migration6 - fixed naming error in hr fields

Revision ID: 9ffe1ca6dbf8
Revises: 1b696c1efba1
Create Date: 2025-09-01 09:44:47.858785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffe1ca6dbf8'
down_revision: Union[str, Sequence[str], None] = '1b696c1efba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr', sa.Column('company', sa.String(), nullable=False))
    op.drop_column('hr', 'Company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr', sa.Column('Company', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hr', 'company')
    # ### end Alembic commands ###
