"""migration3 - changed relation between resume and seeker to be one to many

Revision ID: f770cf7f3e93
Revises: 1408a3ed85e7
Create Date: 2025-08-31 17:54:28.028748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f770cf7f3e93'
down_revision: Union[str, Sequence[str], None] = '1408a3ed85e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeker_resume_association')
    op.add_column('resume', sa.Column('seeker_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resume', 'seeker', ['seeker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'seeker_id')
    op.create_table('seeker_resume_association',
    sa.Column('seeker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name=op.f('seeker_resume_association_resume_id_fkey')),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker.id'], name=op.f('seeker_resume_association_seeker_id_fkey')),
    sa.PrimaryKeyConstraint('seeker_id', 'resume_id', name=op.f('seeker_resume_association_pkey'))
    )
    # ### end Alembic commands ###
